Repository graphql-rust/juniper, pull requests merged in 2020-06, with the labels that each got.

#674 Upgrade bson crate to 0.15.0
  juniper/CHANGELOG.md
  juniper/Cargo.toml
  juniper/src/integrations/bson.rs
Labels: enhancement

#675 Pull request #662's entry in CHANGELOG pointed to incorrect link.
  juniper/CHANGELOG.md
Labels: docs

#628 Added a normalization of subscriptions endpoint in graphiql_source
  juniper/CHANGELOG.md
  juniper/src/http/graphiql.rs
Labels: enhancement, integration

#678 Updated bson crate to 1.0.0
  juniper/CHANGELOG.md
  juniper/Cargo.toml
Labels: enhancement

#680 Relax redundant 'static lifetime bounds on ScalarValue in juniper_subscriptions::Coordinator
  juniper/src/http/mod.rs
  juniper_subscriptions/Cargo.toml
  juniper_subscriptions/src/lib.rs
  juniper_warp/src/lib.rs
Labels: enhancement

#681 fix unions with custom scalar values
  integration_tests/codegen_fail/fail/union/enum_non_object_variant.stderr
  integration_tests/codegen_fail/fail/union/enum_same_type_ugly.stderr
  integration_tests/codegen_fail/fail/union/struct_non_object_variant.stderr
  integration_tests/codegen_fail/fail/union/struct_same_type_ugly.stderr
  integration_tests/codegen_fail/fail/union/trait_non_object_variant.stderr
  integration_tests/codegen_fail/fail/union/trait_same_type_ugly.stderr
  integration_tests/juniper_tests/src/codegen/union_attr.rs
  integration_tests/juniper_tests/src/codegen/union_derive.rs
  integration_tests/juniper_tests/src/custom_scalar.rs
  juniper/src/types/marker.rs
  juniper_codegen/src/graphql_union/mod.rs
Labels: enhancement

#683 fix: endless poll on an errored ws stream
  juniper_warp/src/lib.rs
Labels: enhancement, integration

#684 Update to_camel_case to respect the rust convention of prefixing '_'
  juniper/src/util.rs
  juniper_codegen/src/util/mod.rs
Labels: api, enhancement

#685 Decouple object safe part from GraphQLType
  integration_tests/juniper_tests/src/codegen/derive_input_object.rs
  juniper/CHANGELOG.md
  juniper/src/executor/mod.rs
  juniper/src/http/mod.rs
  juniper/src/integrations/mod.rs
  juniper/src/lib.rs
  juniper/src/macros/interface.rs
  juniper/src/macros/subscription_helpers.rs
  juniper/src/macros/tests/util.rs
  juniper/src/schema/schema.rs
  juniper/src/schema/translate/graphql_parser.rs
  juniper/src/tests/model.rs
  juniper/src/tests/type_info_tests.rs
  juniper/src/types/async_await.rs
  juniper/src/types/base.rs
  juniper/src/types/containers.rs
  juniper/src/types/pointers.rs
  juniper/src/types/scalars.rs
  juniper/src/types/subscriptions.rs
  juniper/src/validation/rules/overlapping_fields_can_be_merged.rs
  juniper/src/validation/test_harness.rs
  juniper/src/value/scalar.rs
  juniper_codegen/src/derive_scalar_value.rs
  juniper_codegen/src/graphql_union/mod.rs
  juniper_codegen/src/impl_scalar.rs
  juniper_codegen/src/util/mod.rs
Labels: api, breaking-change, enhancement

#687 Remove internal versions of proc macros
  juniper/src/executor_tests/async_await/mod.rs
  juniper/src/executor_tests/directives.rs
  juniper/src/executor_tests/enums.rs
  juniper/src/executor_tests/executor.rs
  juniper/src/executor_tests/interfaces_unions.rs
  juniper/src/executor_tests/introspection/enums.rs
  juniper/src/executor_tests/introspection/input_object.rs
  juniper/src/executor_tests/introspection/mod.rs
  juniper/src/executor_tests/variables.rs
  juniper/src/integrations/bson.rs
  juniper/src/integrations/chrono.rs
  juniper/src/integrations/url.rs
  juniper/src/integrations/uuid.rs
  juniper/src/lib.rs
  juniper/src/macros/tests/args.rs
  juniper/src/macros/tests/field.rs
  juniper/src/macros/tests/impl_object.rs
  juniper/src/macros/tests/impl_subscription.rs
  juniper/src/macros/tests/interface.rs
  juniper/src/macros/tests/union.rs
  juniper/src/parser/tests/document.rs
  juniper/src/parser/tests/value.rs
  juniper/src/schema/model.rs
  juniper/src/schema/schema.rs
  juniper/src/tests/model.rs
  juniper/src/tests/schema.rs
  juniper/src/tests/subscriptions.rs
  juniper/src/types/base.rs
  juniper/src/types/scalars.rs
  juniper/src/validation/test_harness.rs
  juniper/src/value/scalar.rs
  juniper_codegen/src/derive_enum.rs
  juniper_codegen/src/derive_input_object.rs
  juniper_codegen/src/derive_object.rs
  juniper_codegen/src/derive_scalar_value.rs
  juniper_codegen/src/graphql_union/attr.rs
  juniper_codegen/src/graphql_union/derive.rs
  juniper_codegen/src/graphql_union/mod.rs
  juniper_codegen/src/impl_object.rs
  juniper_codegen/src/impl_scalar.rs
  juniper_codegen/src/lib.rs
  juniper_codegen/src/util/mod.rs
  juniper_codegen/src/util/mode.rs
Labels: enhancement

#688 Strip redundant Send/Sync bounds
  examples/basic_subscriptions/src/main.rs
  examples/warp_subscriptions/Cargo.toml
  examples/warp_subscriptions/src/main.rs
  juniper/Cargo.toml
  juniper/src/executor/mod.rs
  juniper/src/http/mod.rs
  juniper/src/lib.rs
  juniper/src/macros/tests/impl_object.rs
  juniper/src/macros/tests/impl_subscription.rs
  juniper/src/macros/tests/util.rs
  juniper/src/schema/schema.rs
  juniper/src/types/async_await.rs
  juniper/src/types/base.rs
  juniper/src/types/containers.rs
  juniper/src/types/pointers.rs
  juniper/src/types/scalars.rs
  juniper/src/types/subscriptions.rs
  juniper_actix/examples/actix_server.rs
  juniper_actix/src/lib.rs
  juniper_codegen/src/derive_scalar_value.rs
  juniper_codegen/src/graphql_union/mod.rs
  juniper_codegen/src/impl_scalar.rs
  juniper_codegen/src/util/mod.rs
  juniper_hyper/examples/hyper_server.rs
  juniper_hyper/src/lib.rs
  juniper_rocket/src/lib.rs
  juniper_rocket_async/examples/rocket_server.rs
  juniper_rocket_async/src/lib.rs
  juniper_subscriptions/src/lib.rs
  juniper_warp/examples/warp_server.rs
  juniper_warp/src/lib.rs
Labels: api, enhancement, integration
