Repository graphql-rust/juniper, pull requests merged in 2020-10, with the labels that each got.

#777 Fix parsing f64 from Scalar::Int
  juniper/src/types/scalars.rs
Labels: enhancement

#519 chrono-tz feature: Implement GraphQLType for chrono-tz
  README.md
  juniper/CHANGELOG.md
  juniper/Cargo.toml
  juniper/src/integrations/chrono_tz.rs
  juniper/src/integrations/mod.rs
  juniper_codegen/src/util/mod.rs
Labels: enhancement, integration

#790 Remove redundant `extern crate` usages
  benches/bench.rs
  docs/book/tests/Cargo.toml
  docs/book/tests/build.rs
  examples/warp_async/Cargo.toml
  integration_tests/async_await/Cargo.toml
  integration_tests/juniper_tests/Cargo.toml
  integration_tests/juniper_tests/src/custom_scalar.rs
  juniper/Cargo.toml
  juniper/Makefile.toml
  juniper/benches/bench.rs
  juniper/src/executor/mod.rs
  juniper/src/http/mod.rs
  juniper/src/lib.rs
  juniper/src/value/mod.rs
  juniper/src/value/scalar.rs
  juniper_actix/Cargo.toml
  juniper_actix/Makefile.toml
  juniper_actix/src/lib.rs
  juniper_benchmarks/Cargo.toml
  juniper_benchmarks/Makefile.toml
  juniper_benchmarks/benches/benchmark.rs
  juniper_codegen/Cargo.toml
  juniper_codegen/src/lib.rs
  juniper_graphql_ws/Cargo.toml
  juniper_graphql_ws/src/client_message.rs
  juniper_graphql_ws/src/lib.rs
  juniper_hyper/Cargo.toml
  juniper_hyper/src/lib.rs
  juniper_iron/Cargo.toml
  juniper_iron/examples/iron_server.rs
  juniper_iron/src/lib.rs
  juniper_rocket/Cargo.toml
  juniper_rocket/src/lib.rs
  juniper_rocket/tests/custom_response_tests.rs
  juniper_rocket_async/Cargo.toml
  juniper_rocket_async/src/lib.rs
  juniper_subscriptions/Cargo.toml
  juniper_warp/Cargo.toml
  juniper_warp/Makefile.toml
  juniper_warp/src/lib.rs
Labels: enhancement

#795 Add ability to distinguish between implicit and explicit null
  docs/book/content/SUMMARY.md
  docs/book/content/advanced/implicit_and_explicit_null.md
  docs/book/content/advanced/index.md
  integration_tests/juniper_tests/src/explicit_null.rs
  integration_tests/juniper_tests/src/lib.rs
  juniper/CHANGELOG.md
  juniper/src/ast.rs
  juniper/src/lib.rs
  juniper/src/types/base.rs
  juniper/src/types/mod.rs
  juniper/src/types/nullable.rs
  juniper_codegen/src/impl_object.rs
  juniper_codegen/src/util/mod.rs
Labels: api, enhancement
