Repository graphql-rust/juniper, pull requests merged in 2021-12, with the labels that each got.

#1002 Update book links to fix 404
  README.md
Labels: docs

#1001 [GraphQL October 2021] Forbid `__typename` on subscription root
  integration_tests/juniper_tests/src/issue_372.rs
  juniper/CHANGELOG.md
  juniper/src/types/subscriptions.rs
  juniper/src/validation/rules/fields_on_correct_type.rs
Labels: enhancement, breaking-change

#1004 Fix List input coercion rules
  juniper/CHANGELOG.md
  juniper/Cargo.toml
  juniper/src/types/containers.rs
  juniper/src/validation/test_harness.rs
Labels: bug, enhancement, breaking-change

#1006 feat: Add support for the time crate
  README.md
  docs/book/content/types/scalars.md
  juniper/CHANGELOG.md
  juniper/Cargo.toml
  juniper/src/integrations/chrono.rs
  juniper/src/integrations/mod.rs
  juniper/src/integrations/time.rs
  juniper/src/lib.rs
Labels: enhancement, integration

#1003 [GraphQL October 2021] Support `@specifiedBy(url: "...")` directive (#1000)
  integration_tests/codegen_fail/fail/scalar/derive_invalid_url.rs
  integration_tests/codegen_fail/fail/scalar/derive_invalid_url.stderr
  integration_tests/codegen_fail/fail/scalar/impl_invalid_url.rs
  integration_tests/codegen_fail/fail/scalar/impl_invalid_url.stderr
  integration_tests/juniper_tests/src/codegen/derive_scalar.rs
  integration_tests/juniper_tests/src/codegen/impl_scalar.rs
  integration_tests/juniper_tests/src/codegen/scalar_value_transparent.rs
  juniper/CHANGELOG.md
  juniper/src/executor_tests/introspection/mod.rs
  juniper/src/introspection/mod.rs
  juniper/src/introspection/query.graphql
  juniper/src/introspection/query_without_descriptions.graphql
  juniper/src/schema/meta.rs
  juniper/src/schema/model.rs
  juniper/src/schema/schema.rs
  juniper/src/tests/introspection_tests.rs
  juniper/src/tests/schema_introspection.rs
  juniper/src/validation/test_harness.rs
  juniper_codegen/Cargo.toml
  juniper_codegen/src/derive_scalar_value.rs
  juniper_codegen/src/impl_scalar.rs
  juniper_codegen/src/lib.rs
  juniper_codegen/src/util/mod.rs
  juniper_codegen/src/util/span_container.rs
Labels: enhancement, api

#1007 Fix `juniper_codegen_tests`
  integration_tests/codegen_fail/fail/enum/derive_no_fields.stderr
  integration_tests/codegen_fail/fail/input-object/derive_incompatible_object.stderr
  integration_tests/codegen_fail/fail/input-object/derive_no_fields.stderr
  integration_tests/codegen_fail/fail/input-object/derive_no_underscore.stderr
  integration_tests/codegen_fail/fail/input-object/derive_unique_name.stderr
  integration_tests/codegen_fail/fail/interface/argument_double_underscored.stderr
  integration_tests/codegen_fail/fail/interface/argument_non_input_type.stderr
  integration_tests/codegen_fail/fail/interface/argument_wrong_default_array.stderr
  integration_tests/codegen_fail/fail/interface/downcast_method_conflicts_with_external_downcast_fn.stderr
  integration_tests/codegen_fail/fail/interface/downcast_method_wrong_input_args.stderr
  integration_tests/codegen_fail/fail/interface/downcast_method_wrong_return_type.stderr
  integration_tests/codegen_fail/fail/interface/field_double_underscored.stderr
  integration_tests/codegen_fail/fail/interface/field_non_output_return_type.stderr
  integration_tests/codegen_fail/fail/interface/fields_duplicate.stderr
  integration_tests/codegen_fail/fail/interface/implementer_non_object_type.stderr
  integration_tests/codegen_fail/fail/interface/name_double_underscored.stderr
  integration_tests/codegen_fail/fail/interface/no_fields.stderr
  integration_tests/codegen_fail/fail/object/argument_double_underscored.stderr
  integration_tests/codegen_fail/fail/object/argument_non_input_type.stderr
  integration_tests/codegen_fail/fail/object/argument_wrong_default_array.stderr
  integration_tests/codegen_fail/fail/object/attr_field_non_output_return_type.stderr
  integration_tests/codegen_fail/fail/object/attr_fields_duplicate.stderr
  integration_tests/codegen_fail/fail/object/attr_name_double_underscored.stderr
  integration_tests/codegen_fail/fail/object/attr_no_fields.stderr
  integration_tests/codegen_fail/fail/object/derive_field_double_underscored.stderr
  integration_tests/codegen_fail/fail/object/derive_field_non_output_return_type.stderr
  integration_tests/codegen_fail/fail/object/derive_fields_duplicate.stderr
  integration_tests/codegen_fail/fail/object/derive_name_double_underscored.stderr
  integration_tests/codegen_fail/fail/object/derive_no_fields.stderr
  integration_tests/codegen_fail/fail/object/derive_wrong_item.stderr
  integration_tests/codegen_fail/fail/scalar/impl_invalid_url.stderr
  integration_tests/codegen_fail/fail/subscription/argument_double_underscored.stderr
  integration_tests/codegen_fail/fail/subscription/argument_non_input_type.stderr
  integration_tests/codegen_fail/fail/subscription/argument_wrong_default_array.stderr
  integration_tests/codegen_fail/fail/subscription/field_non_output_return_type.stderr
  integration_tests/codegen_fail/fail/subscription/field_not_async.stderr
  integration_tests/codegen_fail/fail/subscription/fields_duplicate.stderr
  integration_tests/codegen_fail/fail/subscription/name_double_underscored.stderr
  integration_tests/codegen_fail/fail/subscription/no_fields.stderr
  integration_tests/codegen_fail/fail/union/derive_wrong_item.stderr
  integration_tests/codegen_fail/fail/union/enum_external_resolver_fn_conflicts_with_variant_external_resolver_fn.stderr
  integration_tests/codegen_fail/fail/union/enum_name_double_underscored.stderr
  integration_tests/codegen_fail/fail/union/enum_no_fields.stderr
  integration_tests/codegen_fail/fail/union/enum_non_object_variant.stderr
  integration_tests/codegen_fail/fail/union/enum_same_type_pretty.stderr
  integration_tests/codegen_fail/fail/union/enum_wrong_variant_field.stderr
  integration_tests/codegen_fail/fail/union/struct_name_double_underscored.stderr
  integration_tests/codegen_fail/fail/union/struct_no_fields.stderr
  integration_tests/codegen_fail/fail/union/struct_non_object_variant.stderr
  integration_tests/codegen_fail/fail/union/trait_fail_infer_context.stderr
  integration_tests/codegen_fail/fail/union/trait_method_conflicts_with_external_resolver_fn.stderr
  integration_tests/codegen_fail/fail/union/trait_name_double_underscored.stderr
  integration_tests/codegen_fail/fail/union/trait_no_fields.stderr
  integration_tests/codegen_fail/fail/union/trait_non_object_variant.stderr
  integration_tests/codegen_fail/fail/union/trait_same_type_pretty.stderr
  integration_tests/codegen_fail/fail/union/trait_with_attr_on_method.stderr
  integration_tests/codegen_fail/fail/union/trait_wrong_method_input_args.stderr
  integration_tests/codegen_fail/fail/union/trait_wrong_method_return_type.stderr
Labels: enhancement

#1008 Add `@deprecated` directive
  juniper/src/schema/model.rs
  juniper/src/tests/introspection_tests.rs
  juniper/src/tests/schema_introspection.rs
Labels: enhancement

#1005 [GraphQL October 2021] Support directives on variable definitions (#1000)
  juniper/CHANGELOG.md
  juniper/src/ast.rs
  juniper/src/parser/document.rs
  juniper/src/schema/model.rs
  juniper/src/tests/schema_introspection.rs
  juniper/src/validation/rules/known_directives.rs
  juniper/src/validation/visitor.rs
Labels: enhancement
