Repository graphql-rust/juniper, pull requests merged in 2024-01, with the labels that each got.

#1237 Stable order in generated schema's SDL (#1134)
  .github/workflows/ci.yml
  book/src/schema/schemas_and_mutations.md
  juniper/CHANGELOG.md
  juniper/Cargo.toml
  juniper/src/schema/model.rs
  juniper/src/schema/translate/graphql_parser.rs
  juniper/src/schema/translate/mod.rs
  juniper/src/tests/fixtures/starwars/schema_language.rs
  juniper/src/tests/fixtures/starwars/starwars.graphql
Labels: enhancement, semver::breaking, k::api

#1212 Lazy look_ahead
  book/src/types/interfaces.md
  juniper/CHANGELOG.md
  juniper/src/executor/look_ahead.rs
  juniper/src/executor/mod.rs
  juniper/src/lib.rs
  juniper_codegen/src/lib.rs
  tests/integration/tests/codegen_interface_attr_trait.rs
  tests/integration/tests/codegen_object_attr.rs
  tests/integration/tests/codegen_subscription_attr.rs
  tests/integration/tests/issue_371.rs
  tests/integration/tests/issue_398.rs
  tests/integration/tests/issue_500.rs
Labels: enhancement, semver::breaking, k::api, k::performance, k::refactor

#1240 refactor: Use auto_enums instead of futures-enum
  juniper/Cargo.toml
  juniper/src/types/async_await.rs
Labels: enhancement, k::dependencies, k::refactor

#1242 refactor: Avoid copying Span when evaluating rules
  juniper/src/validation/multi_visitor.rs
  juniper/src/validation/rules/no_fragment_cycles.rs
  juniper/src/validation/rules/no_undefined_variables.rs
  juniper/src/validation/rules/no_unused_fragments.rs
  juniper/src/validation/rules/unique_input_field_names.rs
  juniper/src/validation/rules/variables_in_allowed_position.rs
  juniper/src/validation/traits.rs
  juniper/src/validation/visitor.rs
Labels: enhancement, k::performance, k::refactor
